imports:
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: en }
    secret:          woZtwiCVoHeQTWXO
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: fr
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     localhost
        port:     
        dbname:   actEnv
        user:     actEnv
        password: azerty
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: smtp
    host:      localhost
    username:  
    password:  

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Imagine Configuration (thumbnails creation)
avalanche_imagine:
    filters:
       admin_list:
           type:    thumbnail
           options: { size: [119,74], mode: outbound}
       actualite:
           type:    thumbnail
           options: { size: [238,148], mode: outbound}
