ActEnvcontactBundle:
    resource: "@ActEnvcontactBundle/Resources/config/routing.yml"
    prefix:   /

ActEnvmainBundle:
    resource: "@ActEnvmainBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
