parameters:
#    act_envcontact.example.class: ActEnv\contactBundle\Example
    contact_email_to: actes.environnement@laposte.net
    contact_email_from: no-reply@actes-environnement.com

services:
#    act_envcontact.example:
#        class: %act_envcontact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
