parameters:
#    act_envcontact.example.class: ActEnv\contactBundle\Example

services:
#    act_envcontact.example:
#        class: %act_envcontact.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
