ActEnvactualiteBundle_front:
    resource: "@ActEnvactualiteBundle/Resources/config/routing_front.yml"
    prefix:   /

ActEnvactualiteBundle_admin:
    resource: "@ActEnvactualiteBundle/Resources/config/routing_admin.yml"
    prefix:   /admin

