ActEnvmainBundle_homepage:
    pattern:  /
    defaults: { _controller: ActEnvmainBundle:Main:index }

_default_activite:
    pattern:  /prestations
    defaults: { _controller: ActEnvmainBundle:Main:activite }

_default_pourqui:
    pattern:  /pourqui
    defaults: { _controller: ActEnvmainBundle:Main:pourqui }

_default_valorisation:
    pattern:  /valorisation
    defaults: { _controller: ActEnvmainBundle:Main:valorisation }

_default_actualite:
    pattern:  /actualite
    defaults: { _controller: ActEnvactualiteBundle:Actualite:actualite }

_default_contact:
    pattern:  /contact
    defaults: { _controller: ActEnvacontactBundle:Contact:contact }
